### ISSUE TITLE
Please test !

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk-test#1]
# Please test !

FLTK developers are encouraged to use this repository for testing. You can edit files, commit, add branches, test pull requests and merges and even rebases, whatever you like.

**_IMPORTANT NOTE !_**

This repository will either be deleted by the end of Juli 2018 or it may be left for further testing. Nothing done here will **automatically** be ported to the official FLTK repository that is still hosted on http://www.fltk.org in subversion.

**Comment by Albrecht-S** [comment]
Hi @MatthiasWM 
I was just playing around with GitHub's user and team management and tried to set up a `team` to manage our developers. I 'invited' you to see how it works. Thanks for following my invitation.
The GitHub management interface for 'organizations' (like FLTK) is a little confusing at first. I hope I got it so far that we can work with it...
@fltk/devs

**Comment by MatthiasWM** [comment]
I tested forking, pull, commit, push in the fork, pull request to fltk, and reviewing, denying, reopening and accepting the pull request. All went very well.

**Comment by Albrecht-S** [comment]
Thanks for testing.
