### ISSUE TITLE
New issue test

### ISSUE THREAD

**Issue by fltkdev** [fltk/fltk-test#10]
Testing fltk.issues gateway threading.
Top level message.

**Comment by fltkdev** [comment]
This is a reply, I think.
Using github interface to reply.

**Comment by erco77** [comment]
On 09/25/18 20:48, fltkdev wrote:
> This is a reply, I think.
> Using github interface to reply.

    Replying via email to github issue.

**Comment by fltkdev** [comment]
Comment from github.
Looks like issues are flat, unless I'm missing something.

**Comment by fltkdev** [comment]
One more.

**Comment by fltkdev** [comment]
You guys "watching" this "fltk-test" project are gonna get a lot of these emails,
as me and Albrecht are trying to setup git + new site.
Feel free to unsubscribe this thread in particular, as it's gonna be used for lots of testing.

**Comment by erco77** [comment]
Erco adding a message to this.

**Comment by fltkdev** [comment]
fltkdev manager adding a message.
(Now enabled "Include your own updates" in issue notifications, which was hiding replies from newsgroup)

**Comment by Albrecht-S** [comment]
On 26.09.2018 06:33 fltkdev wrote:
> fltkdev manager adding a message.
> (Now enabled "Include your own updates" in issue notifications, which 
> was hiding replies from newsgroup)

Replying via mail: trying to see if I get my own message back...

**Comment by Albrecht-S** [comment]
On 26.09.2018 11:09 Albrecht Schlosser wrote:
> On 26.09.2018 06:33 fltkdev wrote:
>  > fltkdev manager adding a message.
>  > (Now enabled "Include your own updates" in issue notifications, which
>  > was hiding replies from newsgroup)
> 
> Replying via mail: trying to see if I get my own message back...

Trying again. Sorry for the noise.

**Comment by fab672000** [comment]
Testing refering to a precise comment in this thread by using the **'Copy URL'** functionality of one particular message here.
The link should allow you to scroll through the long thread and get to that precise comment like [here](https://github.com/fltk/fltk-test/issues/10#issuecomment-424580804)

**Comment by MatthiasWM** [comment]
> You guys "watching" this "fltk-test" project are gonna get a lot of these emails,
> as me and Albrecht are trying to setup git + new site.
> Feel free to unsubscribe this thread in particular, as it's gonna be used for lots of testing.

No worries. Glad to see that this is progressing!

**Comment by erco77** [comment]
Closing; I believe closing should create two messages in fltk.issues on the new server; one for the close, and one for the comment.

**Comment by fltkdev** [comment]
On 27.09.2018 05:33 erco77 wrote:
> Closing; I believe closing should create two messages in fltk.issues on 
> the new server; one for the close, and one for the comment.

Sent by Albrecht via mail reply from fltk.issues:

I tried to close an issue and watched the messages sent by GitHub, and 
AFAICT I didn't get a message that told me that the issue was closed.

I'm not sure if we get close messages if we only use the close button. 
Seems like we'd need to write a comment that /says/ that we closed the 
issue. :-(

**Comment by fltkdev** [comment]
Check your checkboxes in  Edit Profile -> Notifications.
Probably it's not sending you emails about changes you made yourself.
To get those, you'd need to have "Include your own updates" checked, which is off by default IIRC.

Testing the new fltk.issues mail filters.

**Comment by Albrecht-S** [comment]
We need some real UTF-8 text ...
`
|  €     ‚  ƒ  „  …  †  ‡  ˆ  ‰  Š  ‹  Œ     Ž    |
|     ‘  ’  “  ”  •  –  —  ˜  ™  š  ›  œ     ž  Ÿ |
|     ¡  ¢  £  ¤  ¥  ¦  §  ¨  ©  ª  «  ¬  ­  ®  ¯ |
|  °  ±  ²  ³  ´  µ  ¶  ·  ¸  ¹  º  »  ¼  ½  ¾  ¿ |
|  À  Á  Â  Ã  Ä  Å  Æ  Ç  È  É  Ê  Ë  Ì  Í  Î  Ï |
|  Ð  Ñ  Ò  Ó  Ô  Õ  Ö  ×  Ø  Ù  Ú  Û  Ü  Ý  Þ  ß |
|  à  á  â  ã  ä  å  æ  ç  è  é  ê  ë  ì  í  î  ï |
|  ð  ñ  ò  ó  ô  õ  ö  ÷  ø  ù  ú  û  ü  ý  þ  ÿ |
+-------------------------------------------------+
`

This should  not be proportional spacing but I don't know how to use a fixed font.
Unless `code` is enough...

**Comment by Albrecht-S** [comment]
Reopen issue #10.

**Comment by Albrecht-S** [comment]
Issue is now open.

**Comment by Albrecht-S** [comment]
Close this issue with the close button...
(Close and comment).

**Comment by Albrecht-S** [comment]
Note: there's a comment to my comment:
Albrecht-S closed this 12 seconds ago.

**Comment by Albrecht-S** [comment]
Note to Greg: I didn't see my **edit/update** of the comment "We need some real UTF-8 text ...", neither in my personal mail nor in our newsfeed. Did you see it, or do you have an idea? Don't we get edits/updates from GitHub?

**Comment by fltkdev** [comment]
The message with all the utf8 test text is definitely in the newsgroup; I checked it on both the website and via NNTP.
On the new test server (that only you and I are configured to see, in case others are listening) it's here:
https://www.fltk.org/newsgroups.php?s1+gfltk.issues+v2
If you're not seeing the messages in NNTP, it's probably because it's showing you an old pre-reset cache that you may have to clear by (1) Unsubscribe, (2) close thunderbird, (3) Go into your home directory, find the cache dir for the newsgroup and remove it, (4) open tbird and re-subscribe.

**Comment by fltkdev** [comment]
By 'update', did you mean you edited it?
If so, yeah, I don't know what behavior that might cause for the newsgroup.
I don't know how edits are handled.. I don't think they are via email.

**Comment by fltkdev** [comment]
Confirmed editing does not generate emails.
There's actually two open issues for the github UI about this, so this may change in the future:
```
       1) https://github.com/isaacs/github/issues/954
       2) https://github.com/isaacs/github/issues/310
```

**Comment by Albrecht-S** [comment]
Greg, come to chat please!

**Comment by erco77** [comment]
On 09/28/18 17:11, Albrecht Schlosser wrote:
> Greg, come to chat please!

ok, gimmie a minute


-- 
Greg Ercolano, erco@seriss.com
Seriss Corporation
Rush Render Queue, http://seriss.com/rush/

Skype: ercolano77
  Tel: +1 626-576-0010 ext.23
  Fax: +1 626-576-0020
  Cel: +1 310-266-8906
