### ISSUE TITLE
Threading test

### ISSUE THREAD

**Issue by fltkdev** [fltk/fltk-test#11]
This is the top level message created in github by fltkdev.

**Comment by fltkdev** [comment]
Simple reply in github by fltkdev.

**Comment by erco77** [comment]
Simple reply in github by erco.

**Comment by erco77** [comment]
On 09/25/18 21:35, fltkdev wrote:
> Simple reply in github by fltkdev.

    Erco replying by email to the above message.

**Comment by fltkdev** [comment]
Closing this issue, just to see how it ends up in the newsgroup.

**Comment by fltkdev** [comment]
Reopening test issue.

**Comment by fltkdev** [comment]
When an event is opened/closed, two emails are sent;
one with the comment, the other with the event ("opend", or "closed").
Modified the filters to include both in fltk.issues group.

**Comment by fltkdev** [comment]
I'm using a closing comment, and closing again.

**Comment by fltkdev** [comment]
Comment after close.
