### ISSUE TITLE
Test by Albrecht - please ignore...

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk-test#7]
This is a test issue. Please ignore if you're not involved in this test.

**Comment by Albrecht-S** [comment]
I just added the "question" label to see if we get notifications about such changes.

**Comment by Albrecht-S** [comment]
On 26.09.2018 11:32 Albrecht Schlosser wrote:
> I just added the "question" label to see if we get notifications about 
> such changes.

:-(

Obviously no automatic notification about added labels.

**Comment by Albrecht-S** [comment]
Just another test.
xxx

**Comment by fltkdev** [comment]
Yet another test after unsubscribing.
(Greg, see PM).
yyy

**Comment by Albrecht-S** [comment]
Closing this issue now. If anybody feels inclined to test please feel free to open another issue.

Note that this repo will be archived or deleted in the near future...
